hcs_n_sequential_passwords/hcs_n_sequential_passwords/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from n_sequential_passwords import views

urlpatterns = [
    path('', views.index, name="index"),
    path('n_sequential_passwords/', include('n_sequential_passwords.urls')),
    path('admin/', admin.site.urls),
]

hcs_n_sequential_passwords/n_sequential_passwords/urls.py
from django.urls import path
from n_sequential_passwords import views

app_name = 'n_sequential_passwords'

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('pin/', views.pin_view, name='pin'),
    path('password/', views.password_view, name='password'),
    path('pattern_lock/', views.pattern_lock, name="pattern_lock"),
    path('start/', views.start, name="start"),
    path('password_1/', views.password_1_view, name="password_1"),
    path('pin_1/', views.pin_1_view, name="pin_1"),
    path('password_2_1/', views.password_2_view_1, name="password_2_1"),
    path('pin_2/', views.pin_2_view, name="pin_2"),
    path('password_2_2/', views.password_2_view_2, name="password_2_2"),
    path('password_2password2pin_1/', views.password_2password2pin_view_1, name="password_2password2pin_1"),
    path('password_2password2pin_2/', views.password_2password2pin_view_2, name="password_2password2pin_2"),
    path('pin_2password2pin_1/', views.pin_2password2pin_view_1, name="pin_2password2pin_1"),
    path('pin_2password2pin_2/', views.pin_2password2pin_view_2, name="pin_2password2pin_2"),
    path('pin_2pin_1/', views.pin_2pin_view_1, name="pin_2pin_1"),
    path('pin_2pin_2/', views.pin_2pin_view_2, name="pin_2pin_2"),
    path('pin_3pin_1/', views.pin_3pin_view_1, name="pin_3pin_1"),
    path('pin_3pin_2/', views.pin_3pin_view_2, name="pin_3pin_2"),
    path('pin_3pin_3/', views.pin_3pin_view_3, name="pin_3pin_3"),
    path('pin_4pin_1/', views.pin_4pin_view_1, name="pin_4pin_1"),
    path('pin_4pin_2/', views.pin_4pin_view_2, name="pin_4pin_2"),
    path('pin_4pin_3/', views.pin_4pin_view_3, name="pin_4pin_3"),
    path('pin_4pin_4/', views.pin_4pin_view_4, name="pin_4pin_4"),
    path('password_2password_1/', views.password_2password_view_1, name="password_2password_1"),
    path('password_2password_2/', views.password_2password_view_2, name="password_2password_2"),
    path('password_3password_1/', views.password_3password_view_1, name="password_3password_1"),
    path('password_3password_2/', views.password_3password_view_2, name="password_3password_2"),
    path('password_3password_3/', views.password_3password_view_3, name="password_3password_3"),
    path('password_4password_1/', views.password_4password_view_1, name="password_4password_1"),
    path('password_4password_2/', views.password_4password_view_2, name="password_4password_2"),
    path('password_4password_3/', views.password_4password_view_3, name="password_4password_3"),
    path('password_4password_4/', views.password_4password_view_4, name="password_4password_4"),
    path('success/', views.success, name='success'),
    path('start/', views.start, name="start"),
    path('timer/', views.timer, name='timer_view'),
    path('prompt/', views.prompt, name='promt'),
]

hcs_n_sequential_passwords/n_sequential_passwords/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.TextField(blank=True)
    pattern_lock = models.JSONField(blank=True)
    pin = models.PositiveSmallIntegerField(blank=True)
    password = models.CharField(blank=True, max_length=10)

    def __str__(self):
        return self.username

hcs_n_sequential_passwords/n_sequential_passwords/forms.py
from django import forms
from django.db import models
from django.forms import ModelForm
from n_sequential_passwords.models import User

class PinForm(ModelForm):
    pin = forms.IntegerField(max_value = 5)

    class Meta:
        model = User
        fields = ("username", "pin")

class PasswordForm(ModelForm):
    password = forms.CharField(max_length=16)

    class Meta:
        model = User
        fields = ("username", "password")

class PasswordForm1(forms.Form):
    password = forms.CharField(label='Enter your password', widget=forms.PasswordInput())

class PinForm1(forms.Form):
    pin = forms.IntegerField(label='Enter your pin', widget=forms.PasswordInput())

hcs_n_sequential_passwords/n_sequential_passwords/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .forms import PinForm, PasswordForm, PinForm1, PasswordForm1

combos = {"pin": ["604287"],
          "password": ["&BDY4s$v!v4s"],
          "pin + pin": ["479367", "710441"],
          "pin + pin + pin": ["123456", "869632", "918423"],
          "pin + pin + pin + pin": ["351984", "812595", "918423", "869632"],
          "password + password": ["^pP3@BeHSoP4", "aVE&!ATu4emz"],
          "password + password + password": ["&Ew3Rjtjkqn$", "5##kxTtuL&jD", "9d^zKtHPh%5z"],
          "password + password + password + password": ["XkX67as#HgVP", "s@8@ptuQ!2@f", "9d^zKtHPh%5z", "5##kxTtuL&jD"],
          "password +pin": ["&BDY4s$v!v4s", "604287"],
          "password +pin + password + pin": ["^pP3@BeHSoP4", "479367", "aVE&!ATu4emz", "710441"],
          "password +pin + password": ["^pP3@BeHSoP4", "604287", "aVE&!ATu4emz"],}

def index(request):
    return render(request, 'n_sequential_passwords/index.html')

def pattern_lock(request):
    return render(request, 'n_sequential_passwords/pattern_lock.html')

def start(request):
    return render(request, 'n_sequential_passwords/start.html')

def success(request):
    return render(request, 'n_sequential_passwords/success.html')

def pin_view(request):
    if request.method == "POST":
        form = PinForm1(request.POST)
        if form.is_valid():
            pin = form.cleaned_data['pin']
            if str(pin) == combos["pin"][0]:
                request.session["pin"] = pin
                return redirect("/n_sequential_passwords/success")
            else:
                with open("passwords.txt", "a") as f:
                    f.write(str(pin) + "\n")
    else:
        form = PinForm1()

    return render(request, 'n_sequential_passwords/pin.html', {'form': form})

def password_view(request):
    if request.method == "POST":
        form = PasswordForm1(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            if password == combos["password"][0]:
                request.session["password"] = password
                return redirect("/n_sequential_passwords/success")
            else:
                with open("passwords.txt", "a") as f:
                    f.write(password + "\n")
        
    else:
        form = PasswordForm1()

    return render(request, 'n_sequential_passwords/password.html', {'form': form})

def pin_2pin_view_1(request):
    if request.method == "POST":
        form = PinForm1(request.POST)
        if form.is_valid():
            pin = form.cleaned_data['pin']
            if str(pin) == combos["pin + pin"][0]:
                request.session["pin_2pin"] = pin
                return redirect("/n_sequential_passwords/pin_2pin_2")
            else:
                with open("passwords.txt", "a") as f:
                    f.write(str(pin) + "\n")
    else:
        form = PinForm1()

    return render(request, 'n_sequential_passwords/pin_2pin_1.html', {'form': form})

def pin_2pin_view_2(request):
    if request.method == "POST":
        form = PinForm1(request.POST)
        if form.is_valid():
            pin = form.cleaned_data['pin']
            if str(pin) == combos["pin + pin"][1]:
                request.session["pin_2pin_2"] = pin
                return redirect("/n_sequential_passwords/success")
            else:
                with open("passwords.txt", "a") as f:
                    f.write(str(pin) + "\n")
    else:
        form = PinForm1()

    return render(request, 'n_sequential_passwords/pin_2pin_2.html', {'form': form})

def pin_3pin_view_1(request):
    if request.method == "POST":
        form = PinForm1(request.POST)
        if form.is_valid():
            pin = form.cleaned_data['pin']
            if str(pin) == combos["pin + pin + pin"][0]:
                request.session["pin_3pin_1"] = pin
                return redirect("/n_sequential_passwords/pin_3pin_2")
            else:
                with open("passwords.txt", "a") as f:
                    f.write(str(pin) + "\n")
    else:
        form = PinForm1()

    return render(request, 'n_sequential_passwords/pin_3pin_1.html', {'form': form})

def pin_3pin_view_2(request):
    if request.method == "POST":
        form = PinForm1(request.POST)
        if form.is_valid():
            pin = form.cleaned_data['pin']
            if str(pin) == combos["pin + pin + pin"][1]:
                request.session["pin_3pin_2"] = pin
                return redirect("/n_sequential_passwords/pin_3pin_3")
            else:
                with open("passwords.txt", "a") as f:
                    f.write(str(pin) + "\n")
    else:
        form = PinForm1()
    return render(request, 'n_sequential_passwords/pin_3pin_2.html', {'form': form})

def pin_3pin_view_3(request):
    if request.method == "POST":
        form = PinForm1(request.POST)
        if form.is_valid():
            pin = form.cleaned_data['pin']
            if str(pin) == combos["pin + pin + pin"][2]:
                request.session["pin_3pin_3"] = pin
                return redirect("/n_sequential_passwords/success")
            else:
                with open("passwords.txt", "a") as f:
                    f.write(str(pin) + "\n")
    else:
        form = PinForm1()
    return render(request, 'n_sequential_passwords/pin_3pin_3.html', {'form': form})

def pin_4pin_view_1(request):
    if request.method == "POST":
        form = PinForm1(request.POST)
        if form.is_valid():
            pin = form.cleaned_data['pin']
            if str(pin) == combos["pin + pin + pin + pin"][0]:
                request.session["pin_4pin_1"] = pin
                return redirect("/n_sequential_passwords/pin_4pin_2")
            else:
                with open("passwords.txt", "a") as f:
                    f.write(str(pin) + "\n")
    else:
        form = PinForm1()
    return render(request, 'n_sequential_passwords/pin_4pin_1.html', {'form': form})

def pin_4pin_view_2(request):
    if request.method == "POST":
        form = PinForm1(request.POST)
        if form.is_valid():
            pin = form.cleaned_data['pin']
            if str(pin) == combos["pin + pin + pin + pin"][1]:
                request.session["pin_4pin_2"] = pin
                return redirect("/n_sequential_passwords/pin_4pin_3")
            else:
                with open("passwords.txt", "a") as f:
                    f.write(str(pin) + "\n")
    else:
        form = PinForm1()
    return render(request, 'n_sequential_passwords/pin_4pin_2.html', {'form': form})

def pin_4pin_view_3(request):
    if request.method == "POST":
        form = PinForm1(request.POST)
        if form.is_valid():
            pin = form.cleaned_data['pin']
            if str(pin) == combos["pin + pin + pin + pin"][2]:
                request.session["pin_4pin_3"] = pin
                return redirect("/n_sequential_passwords/pin_4pin_4")
            else:
                with open("passwords.txt", "a") as f:
                    f.write(str(pin) + "\n")
    else:
        form = PinForm1()
    return render(request, 'n_sequential_passwords/pin_4pin_3.html', {'form': form})

def pin_4pin_view_4(request):
    if request.method == "POST":
        form = PinForm1(request.POST)
        if form.is_valid():
            pin = form.cleaned_data['pin']
            if str(pin) == combos["pin + pin + pin + pin"][3]:
                request.session["pin_4pin_4"] = pin
                return redirect("/n_sequential_passwords/success")
            else:
                with open("passwords.txt", "a") as f:
                    f.write(str(pin) + "\n")
    else:
        form = PinForm1()
    return render(request, 'n_sequential_passwords/pin_4pin_4.html', {'form': form})

def password_2password_view_1(request):
    if request.method == "POST":
        form = PasswordForm1(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            if password == combos["password + password"][0]:
                request.session["password_2password_1"] = password
                return redirect("/n_sequential_passwords/password_2password_2")
            else:
                with open("passwords.txt", "a") as f:
                    f.write(password + "\n")
    else:
        form = PasswordForm1()

    return render(request, 'n_sequential_passwords/password_2password_1.html', {'form': form})

def password_2password_view_2(request):
    if request.method == "POST":
        form = PasswordForm1(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            if password == combos["password + password"][1]:
                request.session["password_2password_2"] = password
                return redirect("/n_sequential_passwords/success")
            else:
                with open("passwords.txt", "a") as f:
                    f.write(password + "\n")
    else:
        form = PasswordForm1()

    return render(request, 'n_sequential_passwords/password_2password_2.html', {'form': form})

def password_3password_view_1(request):
    if request.method == "POST":
        form = PasswordForm1(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            if password == combos["password + password + password"][0]:
                request.session["password_3password_1"] = password
                return redirect("/n_sequential_passwords/password_3password_2")
            else:
                with open("passwords.txt", "a") as f:
                    f.write(password + "\n")
    else:
        form = PasswordForm1()

    return render(request, 'n_sequential_passwords/password_3password_1.html', {'form': form})

def password_3password_view_2(request):
    if request.method == "POST":
        form = PasswordForm1(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']

hcs_n_sequential_passwords/templates/n_sequential_passwords/index.html
<!DOCTYPE html>
<html>
    <head><title>Index</title></head>
    <body>
        Hello! Welcome to the N Sequential Passwords task.
        <div>
            <a href="/pattern_lock/">Pattern Lock</a>
        </div>
        <div>
            <a href="/n_sequential_passwords/pin">One-step (pin only)</a>
        </div>
        <div>
          <a href="/n_sequential_passwords/password">One-step (password only)</a>
      </div>
        <div>
            <a href="/n_sequential_passwords/password_1">Two-step (password + pin)</a>
        </div>
        <div>
          <a href="/n_sequential_passwords/password_2_1">Three-step (password + pin + password)</a>
      </div>
      <div>
        <a href="/n_sequential_passwords/password_2password2pin_1">Four-step (password + pin + password + pin)</a>
    </div>
      <div>
        <a href="/n_sequential_passwords/pin_2pin_1">Two-step (pin + pin)</a>
      </div> 
      <div>
        <a href="/n_sequential_passwords/pin_3pin_1">Three-step (pin + pin + pin)</a>
      </div>
      <div>
        <a href="/n_sequential_passwords/pin_4pin_1">Four-step (pin + pin + pin + pin)</a>
      </div>  
      <div>
        <a href="/n_sequential_passwords/password_2password_1">Two-step (password + password)</a>
      </div> 
      <div>
        <a href="/n_sequential_passwords/password_3password_1">Three-step (password + password + password)</a>
      </div> 
      <div>
        <a href="/n_sequential_passwords/password_4password_1">Four-step (password + password + password + password)</a>
      </div> 
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                  <a class="nav-link" href="/index/">Index</a>
                  <a class="nav-link" href="/start/">Start</a>
                  <a class="nav-link" href="/pin/">Pin</a>
                  <a class="nav-link" href="/pattern_lock/">Pattern Lock</a>
                  <a class="nav-link" href="/timer/">Timer</a>
                  <a class="nav-link" href="/prompt/">Prompt</a>
                </div>
              </div>
            </div>
        </nav>
    </body>
</html>

hcs_n_sequential_passwords/templates/n_sequential_passwords/password_2_1.html
<!DOCTYPE html>
<html>
<head>
    <title>Password 1</title>
</head>
<body>
    <h2>Password 1</h2>
    <form method="post" action="{% url 'n_sequential_passwords:password_2_1' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Next</button>
    </form>
</body>
</html>

hcs_n_sequential_passwords/templates/n_sequential_passwords/password_2password2pin_2.html
<!DOCTYPE html>
<html>
<head>
    <title>Password 2</title>
</head>
<body>
    <h2>Password 2</h2>
    <form method="post" action="{% url 'n_sequential_passwords:password_2password2pin_2' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Next</button>
    </form>
</body>
</html>

hcs_n_sequential_passwords/templates/n_sequential_passwords/password_2password_2.html
<!DOCTYPE html>
<html>
<head>
    <title>Password 2</title>
</head>
<body>
    <h2>Password 2</h2>
    <form method="post" action="{% url 'n_sequential_passwords:password_2password_2' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Next</button>
    </form>
</body>
</html>

hcs_n_sequential_passwords/templates/n_sequential_passwords/password_3password_1.html
<!DOCTYPE html>
<html>
<head>
    <title>Password 1</title>
</head>
<body>
    <h2>Password 1</h2>
    <form method="post" action="{% url 'n_sequential_passwords:password_3password_1' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Next</button>
    </form>
</body>
</html>

hcs_n_sequential_passwords/templates/n_sequential_passwords/password_3password_2.html
<!DOCTYPE html>
<html>
<head>
    <title>Password 2</title>
</head>
<body>
    <h2>Password 2</h2>
    <form method="post" action="{% url 'n_sequential_passwords:password_3password_2' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Next</button>
    </form>
</body>
</html>

hcs_n_sequential_passwords/templates/n_sequential_passwords/password_4password_2.html
<!DOCTYPE html>
<html>
<head>
    <title>Password 2</title>
</head>
<body>
    <h2>Password 2</h2>
    <form method="post" action="{% url 'n_sequential_passwords:password_4password_2' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Next</button>
    </form>
</body>
</html>

hcs_n_sequential_passwords/templates/n_sequential_passwords/password_4password_3.html
<!DOCTYPE html>
<html>
<head>
    <title>Password 3</title>
</head>
<body>
    <h2>Password 3</h2>
    <form method="post" action="{% url 'n_sequential_passwords:password_4password_3' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Next</button>
    </form>
</body>
</html>

hcs_n_sequential_passwords/templates/n_sequential_passwords/pin_2password2pin_2.html
<!DOCTYPE html>
<html>
<head>
    <title>Pin 2</title>
</head>
<body>
    <h2>Pin 2</h2>
    <form method="post" action="{% url 'n_sequential_passwords:pin_2password2pin_2' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Next</button>
    </form>
</body>
</html>

hcs_n_sequential_passwords/templates/n_sequential_passwords/pin_2pin_2.html
<!DOCTYPE html>
<html>
<head>
    <title>Pin 2</title>
</head>
<body>
    <h2>Pin 2</h2>
    <form method="post" action="{% url 'n_sequential_passwords:pin_2pin_2' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Next</button>
    </form>
</body>
</html>

hcs_n_sequential_passwords/templates/n_sequential_passwords/pin_3pin_1.html
<!DOCTYPE html>
<html>
<head>
    <title>Pin 1</title>
</head>
<body>
    <h2>Pin 1</h2>
    <form method="post" action="{% url 'n_sequential_passwords:pin_3pin_1' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Next</button>
    </form>
</body>
</html>

hcs_n_sequential_passwords/templates/n_sequential_passwords/pin_4pin_2.html
<!DOCTYPE html>
<html>
<head>
    <title>Pin 2</title>
</head>
<body>
    <h2>Pin 2</h2>
    <form method="post" action="{% url 'n_sequential_passwords:pin_4pin_2' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Next</button>
    </form>
</body>
</html>

hcs_n_sequential_passwords/templates/n_sequential_passwords/prompt.html
<!DOCTYPE html>
<html>
<head>
    <title>Password Prompt</title>
</head>
<body>
    <form method="post">
        <label for="password1">Enter Password 1:</label><br>
        <input type="password" id="password1" name="password1"><br>
        <label for="pin">Enter PIN:</label><br>
        <input type="text" id="pin" name="pin"><br>
        <label for="password2">Enter Password 2:</label><br>
        <input type="password" id="password2" name="password2"><br>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

hcs_n_sequential_passwords/templates/n_sequential_passwords/timer.html
<!DOCTYPE html>
<html>
<head>
    <title>Timer</title>
    <script>
        var startTime;

        function startTimer() {
            startTime = new Date().getTime();
            document.getElementById("timerButton").style.display = "none";
            document.getElementById("passwordForm").style.display = "block";
        }

        function stopTimer() {
            var endTime = new Date().getTime();
            var timeDiff = endTime - startTime;
            alert("Time taken: " + timeDiff / 1000 + " seconds");
        }
    </script>
</head>
<body>
    <button id="timerButton" onclick="startTimer()">Start Timer</button>
    <form id="passwordForm" method="post" style="display: none;">
        {% csrf_token %}
        <label for="password1">Enter Password 1:</label><br>
        <input type="password" id="password1" name="password1"><br>
        <label for="pin">Enter PIN:</label><br>
        <input type="text" id="pin" name="pin"><br>
        <label for="password2">Enter Password 2:</label><br>
        <input type="password" id="password2" name="password2"><br>
        <input type="submit" value="Submit" onclick="stopTimer()">
    </form>
</body>
</html>